# Generated by Django 6.1.1 on 2026-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('years_at_company', models.FloatField()),
                ('overtime', models.CharField(max_length=10)),
                ('job_satisfaction', models.IntegerField()),
                ('work_life_balance', models.IntegerField()),
                ('promotion', models.CharField(max_length=10)),
                ('manager_support', models.IntegerField()),
                ('salary_satisfaction', models.IntegerField()),
                ('workload', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attrition_prediction', models.CharField(blank=True, max_length=10, null=True)),
                ('attrition_probability', models.FloatField(blank=True, null=True)),
                ('retention_risk', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
